version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./.db:/var/lib/mysql    
    env_file: ./dev.env
    ports:
      - "3306:3306"
    expose:
      - "3306"

  server:
    build: server
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./server:/open-tasks-server/source-code
    env_file: ./dev.env
    links:
      - mysql
    depends_on:
      - mysql

networks:
  default:
    name: open-tasks
